
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discuss_security
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop #creates schema when starting the application and removes it when it ends.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect